# Generated by Django 6.0.3 on 2026-03-16 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coursename', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ScalingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScalinggroupName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=25)),
                ('YearEleven', models.BooleanField()),
                ('YearElvMarkbook', models.BooleanField()),
                ('YearTwelve', models.BooleanField()),
                ('YearTweMarkbook', models.BooleanField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
                ('ScalingGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.scalinggroup')),
            ],
        ),
    ]
