# Generated by Django 6.0.3 on 2026-03-18 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssementName', models.CharField(max_length=10)),
                ('Weighting', models.PositiveIntegerField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.unitgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ContentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContentName', models.CharField(max_length=10)),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.unitgroup')),
            ],
        ),
        migrations.CreateModel(
            name='UnitGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoalName', models.CharField(max_length=50)),
                ('GoalDescription', models.CharField()),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.unitgroup')),
            ],
        ),
    ]
