# Generated by Django 6.0.3 on 2026-05-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_assements_contentgroup_unitgoals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('test', 'this is a test')]},
        ),
    ]
