# Generated by Django 6.0.3 on 2026-05-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitgroup',
            name='Published',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
