# Generated by Django 6.0.3 on 2026-05-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_unitgroup_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
